<?php

return [
    'tax_rate' => 11,
    'service_charge' => 0,
    'points_earn_per_amount' => 10000,
    'points_per_rupiah' => 1,
    'points_redeem_value' => 100,
    'currency' => 'IDR',
    'order_prefix' => 'ORD',
    'production_prefix' => 'PROD',
    'transfer_prefix' => 'TRF',
    'opname_prefix' => 'OPN',
    'waste_prefix' => 'WST',

    'roles' => [
        'super_admin' => 'Super Admin',
        'admin' => 'Admin',
        'outlet_manager' => 'Outlet Manager',
        'cashier' => 'Cashier',
        'captain' => 'Captain Order',
        'kitchen' => 'Kitchen Checker',
        'bar' => 'Bar Checker',
    ],

    'permissions' => [
        'dashboard.view',
        'pos.access',
        'orders.view',
        'orders.manage',
        'orders.checkout',
        'orders.check',
        'orders.cancel',
        'tables.view',
        'tables.manage',
        'customers.view',
        'customers.manage',
        'marketing.view',
        'marketing.manage',
        'loyalty.view',
        'loyalty.manage',
        'products.view',
        'products.manage',
        'inventory.view',
        'inventory.manage',
        'inventory.approve',
        'production.view',
        'production.manage',
        'printers.view',
        'printers.manage',
        'reports.view',
        'reports.export',
        'users.view',
        'users.manage',
        'roles.manage',
        'outlets.view',
        'outlets.manage',
        'settings.manage',
        'audit.view',
    ],

    'role_permissions' => [
        'super_admin' => ['*'],
        'admin' => [
            'dashboard.view', 'pos.access', 'orders.view', 'orders.manage', 'orders.checkout', 'orders.check', 'orders.cancel',
            'tables.view', 'tables.manage', 'customers.view', 'customers.manage',
            'marketing.view', 'marketing.manage', 'loyalty.view', 'loyalty.manage',
            'products.view', 'products.manage', 'inventory.view', 'inventory.manage', 'inventory.approve',
            'production.view', 'production.manage', 'printers.view', 'printers.manage',
            'reports.view', 'reports.export', 'users.view', 'users.manage',
            'outlets.view', 'outlets.manage', 'settings.manage', 'audit.view',
        ],
        'outlet_manager' => [
            'dashboard.view', 'pos.access', 'orders.view', 'orders.manage', 'orders.checkout', 'orders.check', 'orders.cancel',
            'tables.view', 'tables.manage', 'customers.view', 'customers.manage',
            'marketing.view', 'loyalty.view', 'products.view',
            'inventory.view', 'inventory.manage', 'inventory.approve',
            'production.view', 'production.manage', 'printers.view',
            'reports.view', 'reports.export',
        ],
        'cashier' => [
            'dashboard.view', 'pos.access', 'orders.view', 'orders.manage', 'orders.checkout',
            'tables.view', 'customers.view', 'customers.manage',
        ],
        'captain' => [
            'dashboard.view', 'pos.access', 'orders.view', 'orders.manage',
            'tables.view', 'tables.manage', 'customers.view', 'customers.manage',
        ],
        'kitchen' => [
            'dashboard.view', 'orders.view', 'orders.check', 'production.view', 'production.manage',
        ],
        'bar' => [
            'dashboard.view', 'orders.view', 'orders.check',
        ],
    ],
];
